# -*- coding: utf-8 -*-
"""Session1_BANA310_20250826.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyKES3ANSALlCuV5TweDoMp2LhMLquYY
"""

# this line prints hellow world for me
print('Hello World!')

# This is the first session of the code

'''Hello world!

I am happy to be here

sfef

sdfsdf
'''

# this line prints hellow world for me
# asdfadssdf
# afddfgagfdg

"""Priority of the operations
1. ()
2. power.        2**3.  pow(2,3)
3. multiplication, division  * / % //
4. addition, subtraction.  + -

"""

print(7*2)
print(8*3)

2 + 3*(8**2 +1) - (4*8//4)

